name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.12'}
      - run: pip install fastapi uvicorn
      - run: python -m py_compile api/main.py
      - uses: arduino/arduino-lint-action@v1
        with: {compliance: strict}
